### ISSUE TITLE
usually gets stuck when taking pieces

### ISSUE THREAD

**Issue by Inf4ge** [Sentero-esp12/Lichess-Keyboard-Input#11]
see it mostly when enemy checks ,i cant take any pieces with the king or pawn , and of course, other pieces have the same problem, but they're less likely to be.
And this shit f*cked up my elo

**Comment by TheYoBots** [comment]
It’s not the authors fault this extension doesn’t help you. It ha helped some and didn’t help others. If you don’t want to use this you aren’t compelled in any way to use it, it’s upto you.

Also this is a keyboard extension for lichess. So where does ELO come from? Lichess decides rating by a system known as Glicko-2. https://lichess.org/faq#ratings
