### ISSUE TITLE
Latest lichess updates broke the add on

### ISSUE THREAD

**Issue by eikob** [Sentero-esp12/Lichess-Keyboard-Input#7]
As of today, this add on doesn't work any more. It only highlights the pieces, but does not move them.

There have been at least two commits on lichess working on keyboard entry.

Here's a thread on the forum: https://lichess.org/forum/lichess-feedback/keyboard-bug

**Comment by Sentero-esp12** [comment]
Yes, I plan to either release or make a new developer mode extension (it includes KB): https://github.com/Sentero-esp12/Multi-Premoves-Optimized after I fix it. But it will require browser tweaking and probably won't be available on the Web Store.
