### ISSUE TITLE
Firefox compatability

### ISSUE THREAD

**Issue by mutamamQ** [Sentero-esp12/Lichess-Keyboard-Input#8]
I attempted to port the extension over to Firefox but because of my poor JS knowladge I couldn't do it. Do you have plans to port the extension over?

**Comment by Sentero-esp12** [comment]
What have you tried? I could maybe try to make a Tampermonkey script. I'm not planning to upload it to Web Store or Add-ons, so the only way to use an extension would be to download a developer version of Firefox.

**Comment by mutamamQ** [comment]
Well I only tried editing the manifest.json file to make it compatible and it allowed me to install it but it didn't actually inject the script and I couldn't find out what was wrong. It would be great if you could update the tampermonkey script for it or add Firefox compatability. Also people can install firefox extensions without having the developer build [as shown here](https://riptutorial.com/firefox-addon/example/26613/installing-a-temporary-add-on).

**Comment by Sentero-esp12** [comment]
I ran into the same problem. It would install it but wouldn't actually run the script. I don't understand why

**Comment by Sentero-esp12** [comment]
I've updated the Tampermonkey script. It should probably work.

**Comment by mutamamQ** [comment]
I tested out the script and unfortunately, it didn't work. Tampermonkey gave a lot of errors when I did a syntax search. I think Tampermonkey has problems with $ operator and string concat. I don't really know what the actual problem is and why it doesn't work.

**Comment by Sentero-esp12** [comment]
P.S. If someone makes a version for FireFox, feel free to upload it to Addons store, or distribute your version, or add a link here and I will put it into README. Closing for now
