### ISSUE TITLE
Pieces turn blue but don't move

### ISSUE THREAD

**Issue by kevlu8** [Sentero-esp12/Lichess-Keyboard-Input#9]
When I hover over a square, the piece that I pressed the key for turns blue but doesn't move, like this: 
![image](https://user-images.githubusercontent.com/69993704/103954873-58691c00-5102-11eb-8e27-b1a3cdac2548.png)

**Comment by artyompal** [comment]
This also happens to me. Sometimes the extension gets stucked. If I move mouse in this mode, it makes random moves. Only page reload helps.

**Comment by TheYoBots** [comment]
When you press a key, it should turn blue. It is not meant to move. If you want a piece to move, hover your mouse over the piece that is blue that you want to move and then slide your mouse to the place where you want to make a move.

for example, 
if you want to play e2e4, then click on ‘w’ (which seems to be the command added to move your pawn up. Then hover your mouse to e4. Then it will play a move.

**Comment by kevlu8** [comment]
Yes, I am hovering over the square, but it still won't move.

**Comment by artyompal** [comment]
Now it never moves pieces at all. It used to work but maybe they have changed Lichess site layout or Chrome browser.

**Comment by Sentero-esp12** [comment]
It's possible that in your Lichess settings "how do you move pieces" is set to "drag only". If that's the case, choosing another option should fix this.
